export const MobileImages = [
      {
        src: "/images/album/polaroid1.png",
        type: "image",
        initialX: -140, 
        initialY: 0,
        finalX: -10, 
        finalY: 0, 
        rotation: -8,
        initialScale: 0.7,
      },
      {
        src: "/images/album/polaroid2.png",
        type: "image",
        initialX: 80,
        initialY: -180,
        finalX: 10,
        finalY: 40,
        rotation: 12,
        initialScale: 0.6,
      },
      {
        src: "/images/album/polaroid3.png",
        type: "image",
        initialX: -30,
        initialY: 180,
        finalX: 8,
        finalY: -40,
        rotation: -4,
        initialScale: 0.8,
      },
      {
        src: "/images/album/polaroid4.png",
        type: "image",
        initialX: 150,
        initialY: 50,
        finalX: 25,
        finalY: 8,
        rotation: -4,
        initialScale: 0.8,
      },
      {
        src: "/images/album/polaroid5.png",
        type: "image",
        initialX: -110,
        initialY: -210,
        finalX: -25,
        finalY: -50,
        rotation: -4,
        initialScale: 0.8,
      },
    ];
export const TabletImages = [
      {
        src: "/images/album/polaroid1.png",
        type: "image",
        initialX: -130, 
        initialY: 10,
        finalX: -15, 
        finalY: 0, 
        rotation: -9,
        initialScale: 0.75,
      },
      {
        src: "/images/album/polaroid2.png",
        type: "image",
        initialX: 120,
        initialY: -130,
        finalX: 15,
        finalY: 45,
        rotation: 13,
        initialScale: 0.65,
      },
      {
        src: "/images/album/polaroid3.png",
        type: "image",
        initialX: -20,
        initialY: 120,
        finalX: 12,
        finalY: -45,
        rotation: -4,
        initialScale: 0.85,
      },
      {
        src: "/images/album/polaroid4.png",
        type: "image",
        initialX: 150,
        initialY: 30,
        finalX: 30,
        finalY: 9,
        rotation: -4,
        initialScale: 0.85,
      },
      {
        src: "/images/album/polaroid5.png",
        type: "image",
        initialX: -100,
        initialY: -170,
        finalX: -30,
        finalY: -60,
        rotation: -4,
        initialScale: 0.85,
      },
    ];
  
  export const DesktopImages =  [
      {
        src: "/images/album/polaroid1.png",
        type: "image",
        initialX: -180, 
        initialY: 80,
        finalX: -20, 
        finalY: 0, 
        rotation: -10,
        initialScale: 0.8,
      },
      {
        src: "/images/album/polaroid2.png",
        type: "image",
        initialX: 220,
        initialY: -120,
        finalX: 20,
        finalY: 50,
        rotation: 15,
        initialScale: 0.7,
      },
      {
        src: "/images/album/polaroid3.png",
        type: "image",
        initialX: 50,
        initialY: 140,
        finalX: 15,
        finalY: -50,
        rotation: -5,
        initialScale: 0.9,
      },
      {
        src: "/images/album/polaroid4.png",
        type: "image",
        initialX: 230,
        initialY: 70,
        finalX: 40,
        finalY: 10,
        rotation: -5,
        initialScale: 0.9,
      },
      {
        src: "/images/album/polaroid5.png",
        type: "image",
        initialX: -200,
        initialY: -70,
        finalX: -40,
        finalY: -70,
        rotation: -5,
        initialScale: 0.9,
      },
    ];
  export const DesktopLargeImages =  [
      {
        src: "/images/album/polaroid1.png",
        type: "image",
        initialX: -250, 
        initialY: 40,
        finalX: -20, 
        finalY: 0, 
        rotation: -10,
        initialScale: 0.8,
      },
      {
        src: "/images/album/polaroid2.png",
        type: "image",
        initialX: 180,
        initialY: -120,
        finalX: 20,
        finalY: 50,
        rotation: 15,
        initialScale: 0.7,
      },
      {
        src: "/images/album/polaroid3.png",
        type: "image",
        initialX: -20,
        initialY: 70,
        finalX: 15,
        finalY: -50,
        rotation: -5,
        initialScale: 0.9,
      },
      {
        src: "/images/album/polaroid4.png",
        type: "image",
        initialX: 230,
        initialY: 10,
        finalX: 40,
        finalY: 10,
        rotation: -5,
        initialScale: 0.9,
      },
      {
        src: "/images/album/polaroid5.png",
        type: "image",
        initialX: -190,
        initialY: -100,
        finalX: -40,
        finalY: -70,
        rotation: -5,
        initialScale: 0.9,
      },
    ];